main: main.cpp edi_LinkedList.hpp edi_LinkedNode.hpp edi_List.hpp persona.hpp persona.cpp generarpersona.cpp generarpersona.hpp asignatura.hpp 
	g++ main.cpp generarpersona.cpp persona.cpp  -g -o main