juego.exe : ruleta-ppal.cpp crupier.cpp jugador.cpp ruleta.cpp persona.cpp
	g++ ruleta-ppal.cpp crupier.cpp jugador.cpp ruleta.cpp persona.cpp -o juego.exe

#namespace.exe : ruleta-ppal.cpp namespace.h
#	g++ ruleta-ppal.cpp -o namespace.exe

